<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Autofac" Version="6.4.0" />
      <PackageReference Include="CommandLineParser" Version="2.9.1" />
      <PackageReference Include="Rsdo.StyleCop" Version="1.0.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\core\Rsdo.Concordancer.Data\Rsdo.Concordancer.Data.csproj" />
      <ProjectReference Include="..\..\core\Rsdo.Concordancer.Infrastructure\Rsdo.Concordancer.Infrastructure.csproj" />
      <ProjectReference Include="..\..\core\Rsdo.Concordancer.Services\Rsdo.Concordancer.Services.csproj" />
    </ItemGroup>

</Project>
