<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Autofac" />
      <PackageReference Include="CommandLineParser" />
      <PackageReference Include="Rsdo.StyleCop" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\core\Rsdo.Concordancer.Data\Rsdo.Concordancer.Data.csproj" />
      <ProjectReference Include="..\..\core\Rsdo.Concordancer.Infrastructure\Rsdo.Concordancer.Infrastructure.csproj" />
      <ProjectReference Include="..\..\core\Rsdo.Concordancer.Services\Rsdo.Concordancer.Services.csproj" />
    </ItemGroup>

</Project>
