<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <PackageReference Include="Autofac" />
      <PackageReference Include="EFCore.NamingConventions" />
      <PackageReference Include="FluentValidation" />
      <PackageReference Include="Hangfire.Core" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" />
      <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
      <PackageReference Include="Microsoft.Extensions.Http" />
      <PackageReference Include="Newtonsoft.Json" />
      <PackageReference Include="Npgsql" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Rsdo.Concordancer.Core\Rsdo.Concordancer.Core.csproj" />
    </ItemGroup>

</Project>
