<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <PackageReference Include="Autofac" />
      <PackageReference Include="Microsoft.Extensions.Configuration" />
      <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" />
      <PackageReference Include="OpenSearch.Client" />
      <PackageReference Include="Rsdo.StyleCop" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Rsdo.Concordancer.Core\Rsdo.Concordancer.Core.csproj" />
    </ItemGroup>

</Project>
