<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <PackageReference Include="Autofac" Version="6.4.0" />
      <PackageReference Include="Microsoft.Extensions.Configuration" Version="6.0.1" />
      <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="6.0.1" />
      <PackageReference Include="OpenSearch.Client" Version="1.1.0" />
      <PackageReference Include="Rsdo.StyleCop" Version="1.0.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Rsdo.Concordancer.Core\Rsdo.Concordancer.Core.csproj" />
    </ItemGroup>

</Project>
