<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <PackageReference Include="Autofac" />
      <PackageReference Include="FluentMigrator" />
      <PackageReference Include="FluentMigrator.Runner" />
      <PackageReference Include="FluentMigrator.Runner.Postgres" />
      <PackageReference Include="Npgsql" />
      <PackageReference Include="Rsdo.StyleCop" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Rsdo.Concordancer.Core\Rsdo.Concordancer.Core.csproj" />
    </ItemGroup>

</Project>
