<Project Sdk="Microsoft.NET.Sdk.Web">

    <ItemGroup>
        <PackageReference Include="Autofac" />
        <PackageReference Include="Autofac.Extensions.DependencyInjection" />
        <PackageReference Include="Hangfire" />
        <PackageReference Include="Hangfire.PostgreSql" />
        <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" />
        <PackageReference Include="Serilog.AspNetCore" />
        <PackageReference Include="Serilog.Expressions" />
        <PackageReference Include="Serilog.Settings.Configuration" />
        <PackageReference Include="Serilog.Sinks.Console" />
        <PackageReference Include="Serilog.Sinks.Email" />
        <PackageReference Include="Serilog.Sinks.File" />
        <PackageReference Include="Swashbuckle.AspNetCore" />
        <PackageReference Include="Swashbuckle.AspNetCore.Annotations" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\core\Rsdo.Concordancer.Data\Rsdo.Concordancer.Data.csproj" />
      <ProjectReference Include="..\..\core\Rsdo.Concordancer.Infrastructure\Rsdo.Concordancer.Infrastructure.csproj" />
      <ProjectReference Include="..\..\core\Rsdo.Concordancer.ServiceModel\Rsdo.Concordancer.ServiceModel.csproj" />
      <ProjectReference Include="..\..\core\Rsdo.Concordancer.Services\Rsdo.Concordancer.Services.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="WebApp" />
    </ItemGroup>

    <ItemGroup>
      <None Update="WebApp\build\**">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>
</Project>
